version: 2
updates:
- package-ecosystem: docker
  directory: "/create_aio_app/template/%7B%7Bcookiecutter.project_name%7D%7D"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python
    versions:
    - 3.9.1
    - 3.9.2
    - 3.9.3
